scan_filter_chain:
 - name: box
   type: laser_filters/LaserScanBoxFilter
   params:
     box_frame: base_link
     min_x: -0.28
     max_x: 0.15
     min_y: -0.4
     max_y: 0.4
     min_z: -1.0
     max_z: 1.0   
 - name: range
   type: laser_filters/LaserScanRangeFilter
   params:
     use_message_range_limits: false
     lower_threshold: 0.15
     upper_threshold: 18.0
     upper_replacement_value: 40.0
