#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the following usb connection as /dev/astra    /dev/imu /dev/rplidar*"
echo ""

sudo cp `rospack find volta_control`/10-volta-usb.rules /etc/udev/rules.d


echo ""
echo "Restarting udev"
echo ""
sudo service udev reload
sudo service udev restart
#sudo udevadm trigger --action=change
